@startuml GnssInterfaceImplTests
hide empty members

class GnssInterfaceImpl

class GnssInterfaceImplTests
{
    + void set_serial_interface(SerialInterface<>* serial_interface)
}

class SerialInterfaceMock
{
    + MOCK_METHOD(open);
    + MOCK_METHOD(is_open);
    + MOCK_METHOD(close);
    + MOCK_METHOD(read_line);
}

class SerialInterface<asio::serial_port>

SerialInterface <|-- SerialInterfaceMock
GnssInterfaceImpl o-- "1" SerialInterfaceMock
GnssInterfaceImpl <|-- GnssInterfaceImplTests
@enduml
