@startuml
hide empty members

class SerialInterface<class SerialPort = asio::serial_port>

SerialInterface : virtual SerialInterface() noexcept
SerialInterface : virtual bool open(std::string port, uint64_t baudrate) noexcept
SerialInterface : virtual bool is_open() noexcept
SerialInterface : virtual bool close() noexcept
SerialInterface : virtual bool read_line(std::string& result) noexcept
SerialInterface : virtual std::size_t read_char(char& c, asio::error_code& ec) noexcept

class SerialPort

SerialInterface o-- "1" SerialPort
@enduml
