name: automated_testing

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  ubuntu-build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install apt packages
        run: |
          sudo apt update && sudo apt -y install \
            software-properties-common \
            cmake \
            g++ \
            wget \
            libasio-dev \
            doxygen \
            python3 \
            python3-pip \
            python3-sphinxcontrib.spelling \
            python3-venv

      - uses: ./.github/actions/install-gtest-ubuntu

      - name: Install python packages
        run: pip3 install -r docs/requirements.txt

      - name: Configure project
        run: |
          mkdir build && \
          cd build && \
          cmake .. -DBUILD_DOCUMENTATION=ON -DBUILD_TESTS=ON -DBUILD_EXAMPLES=ON

      - name: Build project
        run: |
          cd build && \
          cmake --build .

      - name: Run tests
        run: |
          cd build && \
          ctest -VV

      - name: Upload documentation
        uses: actions/upload-artifact@v1
        with:
          name: Documentation HTML
          path: build/docs/sphinx/html/
        if: always()
